version: '3'
services:
  mysql-demo:
    container_name: mysql-container
    image: mysql:8.3
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_PASSWORD: "R@zvan3l"
      MYSQL_ROOT_PASSWORD: "R@zvan3l"
