version: '3.1'

services:
  db:
    image: mysql:9.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_USER: user_test
      MYSQL_PASSWORD: User_test
      MYSQL_ROOT_PASSWORD: User_test
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
