version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_USER: user_test
      MYSQL_PASSWORD: User_test
      MYSQL_ROOT_PASSWORD: R@zvan3l
      MYSQL_DATABASE: testdb
    ports:
      - "1111:3306"
    volumes:
      - ./data:/var/lib/mysql
